version: '3'
services:
  mongo:
    image:
  web:
    build: .
    ports:
      - '8080:8000'
    environment:
      -
    links:
      -
    depends_on:
      -
    volumes:
      - .:/
      - /node_modules
